default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: e_commerce_rails-db
  pool: 5
development:
  <<: *default
  database: e_commerce_rails_development

test:
  <<: *default
  database: e_commerce_rails_test

production:
  primary: &primary_production
    <<: *default
    database: e_commerce_rails_production
    username: postgres
    password: password
  cache:
    <<: *primary_production
    database: e_commerce_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: e_commerce_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: e_commerce_rails_production_cable
    migrations_paths: db/cable_migrate
